name: Build and deploy

# For every time master changes
on:
  push:
    branches: [master]

  # Allow manual activation for when it hits the fan
  workflow_dispatch:

jobs:
  build-and-deploy:

    # Refer to: https://github.com/actions/virtual-environments/blob/main/README.md
    runs-on: ubuntu-latest
    steps:
      
        # Login and clone
      - name: Login and clone remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone https://github.com/forkpoweroutlet/genshin-pity-calculator
          cd genshin-pity-calculator

        # Checkout and merge new changes but stage rather than commit
      - name: Get new changes
        run: |
          git checkout gh-pages
          git pull origin master --no-commit --no-ff --allow-unrelated-histories
      
        # Install deps
      - name: Install NPM dependencies
        run: npm install

        # Build JS
      - name: Bundle with Webpack
        run: npm run build
        
        # Add bundle to staging area + commit + push and let the page build from there
      - name: Stage, commit, and push
        run: |
          git add -f build/
          git commit -m "Deploy: `git log -1 --format=%s`"
          git push origin gh-pages
